all:
  vars:
    ansible_user: root
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  children:
    routers:
      hosts:
        gateway-router:
          ansible_host: 10.1.0.1
        ap-repeater:
          ansible_host: 192.168.8.1
    gateway:
      hosts:
        gateway-router:
    access_points:
      hosts:
        ap-repeater:
    openwrt_tailscale_nodes:
      hosts:
        # travel-router:
        #   ansible_host: 10.1.0.50
        # remote-openwrt:
        #   ansible_host: 10.1.0.51
