# Non-secret network settings tracked in plaintext.

network:
  wifi:
    country: GB
    channels:
      "2g": "6"
      "5g": "36"

  gateway_router:
    mgmt_ssid: Gateway Mgmt
    mgmt_encryption: sae-mixed
    mgmt_switch_button_names:
      - BTN_2
      - switch
      - sw1
    lan_management_vlan: 99
    radios_to_disable:
      - radio0
      - radio1
    test_mode:
      enabled: false
      repeater:
        network: wwan
        radio: radio1
        encryption: sae
        radios:
          - radio1
          - radio0
          - radio2
        encryptions:
          - sae
          - sae-mixed
          - psk2
          - psk-mixed
      tailscale_hosts:
        - login.tailscale.com
        - api.tailscale.com
      uplink_wait_seconds: 90
      uplink_poll_interval_seconds: 5
    wan:
      proto: pppoe
      pppoe:
        mtu: '1492'
        vlan_tag: '911'
        parent_if: ''
        service: ''

  vlans:
    - id: 10
      name: servers
      ip: 10.10.0.1
      zone: server_zone
    - id: 20
      name: trusted
      ip: 10.20.0.1
      zone: trusted_zone
    - id: 30
      name: iot
      ip: 10.30.0.1
      zone: iot_zone
    - id: 40
      name: guest
      ip: 10.40.0.1
      zone: guest_zone
    - id: 50
      name: tv_vpn
      ip: 10.50.0.1
      zone: tv_zone

  ap_repeater:
    lan_management_vlan: 99
    ssids:
      - name: trusted_5g
        ssid: Meerkat Manor
        vlan_id: 20
        key: "{{ vault_wifi_key_manor }}"
        device: radio1
        encryption: sae
      - name: iot_2g
        ssid: Meerkat IoT
        vlan_id: 30
        key: "{{ vault_wifi_key_iot }}"
        device: radio0
        encryption: psk2
      - name: guest_2g
        ssid: Meerkat Guest
        vlan_id: 40
        key: "{{ vault_wifi_key_guest }}"
        device: radio0
        encryption: psk-mixed
        isolate: '1'
      - name: guest_5g
        ssid: Meerkat Guest
        vlan_id: 40
        key: "{{ vault_wifi_key_guest }}"
        device: radio1
        encryption: psk-mixed
        isolate: '1'
      - name: tv_vpn_5g
        ssid: Meerkat TV
        vlan_id: 50
        key: "{{ vault_wifi_key_tv | default(vault_wifi_key_guest) }}"
        device: radio1
        encryption: psk-mixed


  mikrotik_crs310:
    bridge_name: bridge
    uplink_interface: ether1
    ap_interface: ether2
    trunk_native_pvid: 99
    access_port_pvids:
      ether3: 20
      ether4: 10
      ether5: 10
      ether6: 30
      ether7: 30
      ether8: 30
      sfp-sfpplus1: 10
      sfp-sfpplus2: 20
    vlan_ids:
      - 10
      - 20
      - 30
      - 40
      - 50
      - 99
    tagged_by_vlan:
      10:
        - ether1
      20:
        - ether1
        - ether2
      30:
        - ether1
        - ether2
      40:
        - ether1
        - ether2
      50:
        - ether1
        - ether2
      99:
        - bridge
    untagged_by_vlan:
      10:
        - ether4
        - ether5
        - sfp-sfpplus1
      20:
        - ether3
        - sfp-sfpplus2
      30:
        - ether6
        - ether7
        - ether8
      99:
        - ether1
        - ether2
    mgmt_vlan_id: 99
    mgmt_ip_cidr: 10.1.0.2/24
    mgmt_gateway: 10.1.0.1
    rollback_delay_minutes: 10

  forwarding_rules:
    - src: trusted_zone
      dest: server_zone
    - src: trusted_zone
      dest: wan
    - src: server_zone
      dest: wan
    - src: iot_zone
      dest: wan
    - src: guest_zone
      dest: wan
    - src: tv_zone
      dest: wan

services:
  tailscale:
    enabled: true
    gateway_router:
      hostname: gateway-router
      advertise_exit_node: true
      advertise_routes:
        - 10.10.0.0/24
        - 10.20.0.0/24
    ap_repeater:
      hostname: ap-repeater
      advertise_exit_node: false
      advertise_routes: []
    oauth:
      tailnet: '-'
      tags:
        - tag:gateway-router
      key_expiry_seconds: 7776000

  adguard:
    enabled: false
    admin_port: 3000
    dns_port: 53
    upstream_dns:
      - https://dns10.quad9.net/dns-query
      - https://1.1.1.1/dns-query
    bootstrap_dns:
      - 9.9.9.9
      - 1.1.1.1

  wireguard_policy:
    enabled: false
    connections:
      - name: surfshark_london
        private_key: "{{ vault_wireguard_private_key_london | default('') }}"
        endpoint_host: uk-lon.prod.surfshark.com
        endpoint_port: 51820
        public_key: "{{ vault_wireguard_public_key_london | default('') }}"
        preshared_key: "{{ vault_wireguard_preshared_key_london | default('') }}"
        allowed_ips:
          - 0.0.0.0/0
        addresses:
          - 10.14.0.2/16
      - name: surfshark_amsterdam
        private_key: "{{ vault_wireguard_private_key_amsterdam | default('') }}"
        endpoint_host: nl-ams.prod.surfshark.com
        endpoint_port: 51820
        public_key: "{{ vault_wireguard_public_key_amsterdam | default('') }}"
        preshared_key: "{{ vault_wireguard_preshared_key_amsterdam | default('') }}"
        allowed_ips:
          - 0.0.0.0/0
        addresses:
          - 10.15.0.2/16
    vlan_map:
      - name: iot_to_amsterdam
        vlan_zone: iot_zone
        subnet: 10.30.0.0/24
        connection_name: surfshark_amsterdam
      - name: trusted_to_london
        vlan_zone: trusted_zone
        subnet: 10.20.0.0/24
        connection_name: surfshark_london
      - name: servers_to_london
        vlan_zone: server_zone
        subnet: 10.10.0.0/24
        connection_name: surfshark_london
      - name: guest_to_london
        vlan_zone: guest_zone
        subnet: 10.40.0.0/24
        connection_name: surfshark_london
      - name: tv_to_amsterdam
        vlan_zone: tv_zone
        subnet: 10.50.0.0/24
        connection_name: surfshark_amsterdam
