# Non-secret network settings tracked in plaintext.

network:
  wifi:
    country: GB

  garage:
    mgmt_ssid: homelab_garage_mngmt
    radios_to_disable:
      - radio0
      - radio1
    test_mode:
      enabled: false
      repeater:
        network: wwan
        radio: radio1
        encryption: sae
        radios:
          - radio1
          - radio0
          - radio2
        encryptions:
          - sae
          - sae-mixed
          - psk2
          - psk-mixed
      tailscale_hosts:
        - login.tailscale.com
        - api.tailscale.com
      uplink_wait_seconds: 90
      uplink_poll_interval_seconds: 5
    wan:
      proto: pppoe
      pppoe:
        mtu: '1492'
        vlan_tag: '911'
        parent_if: ''
        service: ''

  vlans:
    - id: 10
      name: servers
      ip: 10.10.0.1
      zone: server_zone
    - id: 20
      name: trusted
      ip: 10.20.0.1
      zone: trusted_zone
    - id: 30
      name: iot
      ip: 10.30.0.1
      zone: iot_zone
    - id: 99
      name: guest
      ip: 10.99.0.1
      zone: guest_zone

  office_ap:
    ssids:
      - name: manor_5g
        ssid: Meerkat Manor
        vlan_id: 20
        key: "{{ vault_wifi_key_manor }}"
        device: radio1
        encryption: sae
      - name: iot_2g
        ssid: Meerkat IoT
        vlan_id: 30
        key: "{{ vault_wifi_key_iot }}"
        device: radio0
        encryption: psk2
      - name: guest_2g
        ssid: Meerkat Guest
        vlan_id: 99
        key: "{{ vault_wifi_key_guest }}"
        device: radio0
        encryption: psk-mixed
        isolate: '1'
      - name: guest_5g
        ssid: Meerkat Guest
        vlan_id: 99
        key: "{{ vault_wifi_key_guest }}"
        device: radio1
        encryption: psk-mixed
        isolate: '1'

  forwarding_rules:
    - src: trusted_zone
      dest: server_zone
    - src: trusted_zone
      dest: wan
    - src: server_zone
      dest: wan
    - src: iot_zone
      dest: wan
    - src: guest_zone
      dest: wan

services:
  tailscale:
    enabled: true
    garage:
      hostname: router-garage
      advertise_exit_node: true
      advertise_routes:
        - 10.10.0.0/24
        - 10.20.0.0/24
    office_ap:
      hostname: router-office
      advertise_exit_node: false
      advertise_routes: []
    oauth:
      tailnet: '-'
      tags:
        - tag:router-garage
      key_expiry_seconds: 7776000

  adguard:
    enabled: false
    admin_port: 3000
    dns_port: 53
    upstream_dns:
      - https://dns10.quad9.net/dns-query
      - https://1.1.1.1/dns-query
    bootstrap_dns:
      - 9.9.9.9
      - 1.1.1.1

  wireguard_policy:
    enabled: false
    connections:
      - name: surfshark_london
        private_key: "{{ vault_wireguard_private_key_london | default('') }}"
        endpoint_host: uk-lon.prod.surfshark.com
        endpoint_port: 51820
        public_key: "{{ vault_wireguard_public_key_london | default('') }}"
        preshared_key: "{{ vault_wireguard_preshared_key_london | default('') }}"
        allowed_ips:
          - 0.0.0.0/0
        addresses:
          - 10.14.0.2/16
      - name: surfshark_amsterdam
        private_key: "{{ vault_wireguard_private_key_amsterdam | default('') }}"
        endpoint_host: nl-ams.prod.surfshark.com
        endpoint_port: 51820
        public_key: "{{ vault_wireguard_public_key_amsterdam | default('') }}"
        preshared_key: "{{ vault_wireguard_preshared_key_amsterdam | default('') }}"
        allowed_ips:
          - 0.0.0.0/0
        addresses:
          - 10.15.0.2/16
    vlan_map:
      - name: iot_to_amsterdam
        vlan_zone: iot_zone
        subnet: 10.30.0.0/24
        connection_name: surfshark_amsterdam
      - name: trusted_to_london
        vlan_zone: trusted_zone
        subnet: 10.20.0.0/24
        connection_name: surfshark_london
      - name: servers_to_london
        vlan_zone: server_zone
        subnet: 10.10.0.0/24
        connection_name: surfshark_london
      - name: guest_to_london
        vlan_zone: guest_zone
        subnet: 10.99.0.0/24
        connection_name: surfshark_london
