---
- name: Configure Garage Router (Gateway baseline)
  hosts: gateway
  become: false
  gather_facts: false

  vars_files:
    - group_vars/all/network.yml
    - group_vars/all/vault.yml

  vars:
    lan_ip: "10.1.0.1"
    lan_netmask: "255.255.255.0"
    garage_mgmt_ssid_default: "homelab_garage_mngmt"
    garage_wifi_radios_to_disable_default:
      - radio0
      - radio1

  tasks:
    - name: Resolve garage Wi-Fi policy
      ansible.builtin.set_fact:
        garage_mgmt_ssid_effective: "{{ garage_mgmt_ssid | default(garage_mgmt_ssid_default) }}"
        garage_wifi_radios_to_disable_effective: "{{ garage_wifi_radios_to_disable | default(garage_wifi_radios_to_disable_default) }}"

    - name: Set router hostname and timezone
      ansible.builtin.raw: |
        uci set system.@system[0].hostname='router-garage'
        uci set system.@system[0].zonename='Europe/London'
        uci set system.@system[0].timezone='GMT0BST,M3.5.0/1,M10.5.0'

    - name: Rename garage Wi-Fi SSIDs to management label
      ansible.builtin.raw: |
        idx=0
        while uci -q get wireless.@wifi-iface[$idx] >/dev/null 2>&1; do
          uci set wireless.@wifi-iface[$idx].ssid='{{ garage_mgmt_ssid_effective }}'
          idx=$((idx+1))
        done

    - name: Set LAN management interface
      ansible.builtin.raw: |
        uci set network.lan.ipaddr='{{ lan_ip }}'
        uci set network.lan.netmask='{{ lan_netmask }}'

    - name: Ensure VLAN interfaces exist
      ansible.builtin.raw: |
        {% for vlan in vlans %}
        uci -q delete network.vlan{{ vlan.id }}
        uci set network.vlan{{ vlan.id }}='interface'
        uci set network.vlan{{ vlan.id }}.proto='static'
        uci set network.vlan{{ vlan.id }}.device='br-lan.{{ vlan.id }}'
        uci set network.vlan{{ vlan.id }}.ipaddr='{{ vlan.ip }}'
        uci set network.vlan{{ vlan.id }}.netmask='255.255.255.0'
        {% endfor %}

    - name: Ensure DHCP pools exist for routed VLANs
      ansible.builtin.raw: |
        {% for vlan in vlans %}
        uci -q delete dhcp.vlan{{ vlan.id }}
        uci set dhcp.vlan{{ vlan.id }}='dhcp'
        uci set dhcp.vlan{{ vlan.id }}.interface='vlan{{ vlan.id }}'
        uci set dhcp.vlan{{ vlan.id }}.start='100'
        uci set dhcp.vlan{{ vlan.id }}.limit='150'
        uci set dhcp.vlan{{ vlan.id }}.leasetime='12h'
        {% endfor %}

    - name: Configure firewall zones for VLANs
      ansible.builtin.raw: |
        {% for vlan in vlans %}
        uci -q delete firewall.{{ vlan.zone }}
        uci set firewall.{{ vlan.zone }}='zone'
        uci set firewall.{{ vlan.zone }}.name='{{ vlan.zone }}'
        uci set firewall.{{ vlan.zone }}.network='vlan{{ vlan.id }}'
        uci set firewall.{{ vlan.zone }}.input='{{ 'ACCEPT' if vlan.name in ['servers', 'trusted'] else 'REJECT' }}'
        uci set firewall.{{ vlan.zone }}.output='ACCEPT'
        uci set firewall.{{ vlan.zone }}.forward='{{ 'ACCEPT' if vlan.name == 'servers' else 'REJECT' }}'
        {% endfor %}

    - name: Configure inter-zone forwarding rules from vars
      ansible.builtin.raw: |
        idx=0
        while uci -q get firewall.forwarding[$idx] >/dev/null 2>&1; do
          uci -q delete firewall.forwarding[$idx]
        done
        {% for rule in forwarding_rules %}
        uci add firewall forwarding >/dev/null
        uci set firewall.@forwarding[-1].src='{{ rule.src }}'
        uci set firewall.@forwarding[-1].dest='{{ rule.dest }}'
        {% endfor %}

    - name: Add trusted to servers limited management rule
      ansible.builtin.raw: |
        uci -q delete firewall.trusted_to_servers_mgmt
        uci set firewall.trusted_to_servers_mgmt='rule'
        uci set firewall.trusted_to_servers_mgmt.name='Trusted to Servers Web and SSH'
        uci set firewall.trusted_to_servers_mgmt.src='trusted_zone'
        uci set firewall.trusted_to_servers_mgmt.dest='server_zone'
        uci set firewall.trusted_to_servers_mgmt.proto='tcp'
        uci set firewall.trusted_to_servers_mgmt.dest_port='22 80 443'
        uci set firewall.trusted_to_servers_mgmt.target='ACCEPT'

    - name: Disable garage 2.4/5 GHz radios after VLAN and firewall setup
      ansible.builtin.raw: |
        {% for radio in garage_wifi_radios_to_disable_effective %}
        if uci -q get wireless.{{ radio }} >/dev/null 2>&1; then
          uci set wireless.{{ radio }}.disabled='1'
        fi
        {% endfor %}

    - name: Commit UCI changes
      ansible.builtin.raw: |
        uci commit system
        uci commit network
        uci commit dhcp
        uci commit firewall
        uci commit wireless

    - name: Restart firewall and dnsmasq before LAN IP handoff
      ansible.builtin.raw: |
        /etc/init.d/dnsmasq restart || /etc/init.d/dnsmasq start
        /etc/init.d/firewall restart

    - name: Apply delayed network and Wi-Fi reload for safer SSH handoff
      ansible.builtin.raw: |
        nohup sh -c "sleep 2; /etc/init.d/network reload; wifi reload >/dev/null 2>&1 || true" >/dev/null 2>&1 &

    - name: Wait for SSH on post-change management IP (best effort)
      ansible.builtin.wait_for:
        host: "{{ lan_ip }}"
        port: 22
        delay: 4
        timeout: 90
      delegate_to: localhost
      become: false
      register: garage_handoff_wait
      failed_when: false
      changed_when: false

    - name: Show reconnection hint
      ansible.builtin.debug:
        msg: >-
          If your control host route changed during reload, reconnect using
          ssh root@{{ lan_ip }} and rerun with -e ansible_host=192.168.8.1 for
          future factory-reset bootstrap runs.
